# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: lifelog
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: lifelog
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
